/**
 * Gitignore management — update .gitignore with loadout-managed paths.
 *
 * Uses markers to identify the managed section:
 *   # <loadouts>
 *   ...managed paths...
 *   # </loadouts>
 */

import * as path from "node:path";
import * as os from "node:os";
import { fileExists, readFile, writeFile } from "./fs.js";
import { registry } from "../core/registry.js";
import { expandTemplate, type TemplateVars } from "../core/template.js";
import type { Scope } from "../core/types.js";

const START_MARKER = "# <loadouts>";
const END_MARKER = "# </loadouts>";
const HEADER_COMMENT = "# Auto-generated by loadouts. Do not edit this section.";

/**
 * Update .gitignore with loadout-managed paths.
 *
 * - Creates .gitignore if it doesn't exist
 * - Adds or updates the managed section between markers
 * - Preserves all user content outside the markers
 * - Removes the section entirely if managedPaths is empty
 */
export function updateGitignore(
  projectRoot: string,
  managedPaths: string[]
): void {
  const gitignorePath = path.join(projectRoot, ".gitignore");

  // Always include the state file
  const allPaths = [".loadouts/.state.json", ".loadouts/.fallback-applied", ...managedPaths];

  // Sort and deduplicate
  const uniquePaths = [...new Set(allPaths)].sort();

  // Build the managed section content
  const managedSection =
    uniquePaths.length > 0
      ? `${START_MARKER}\n${HEADER_COMMENT}\n${uniquePaths.join("\n")}\n${END_MARKER}`
      : "";

  if (!fileExists(gitignorePath)) {
    // Create new .gitignore with just the managed section
    if (managedSection) {
      writeFile(gitignorePath, managedSection + "\n");
    }
    return;
  }

  // Read existing content
  const content = readFile(gitignorePath);

  // Find existing managed section
  const startIdx = content.indexOf(START_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    // Replace existing section
    const before = content.slice(0, startIdx).trimEnd();
    const after = content.slice(endIdx + END_MARKER.length).trimStart();

    const parts = [before];
    if (managedSection) {
      parts.push(managedSection);
    }
    if (after) {
      parts.push(after);
    }

    // Join with appropriate newlines
    let newContent = parts.filter(Boolean).join("\n\n");
    if (!newContent.endsWith("\n")) {
      newContent += "\n";
    }

    writeFile(gitignorePath, newContent);
  } else {
    // No existing section — append the managed section
    if (!managedSection) return;

    let newContent = content.trimEnd();
    newContent += "\n\n" + managedSection + "\n";
    writeFile(gitignorePath, newContent);
  }
}

/**
 * Remove the loadout-managed section from .gitignore.
 */
export function removeGitignoreSection(projectRoot: string): void {
  updateGitignore(projectRoot, []);
}

/**
 * Get the current managed paths from .gitignore (for testing/inspection).
 */
export function getManagedPaths(projectRoot: string): string[] {
  const gitignorePath = path.join(projectRoot, ".gitignore");

  if (!fileExists(gitignorePath)) {
    return [];
  }

  const content = readFile(gitignorePath);
  const startIdx = content.indexOf(START_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) {
    return [];
  }

  const section = content.slice(startIdx + START_MARKER.length, endIdx);
  return section
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"));
}

/**
 * Compute the gitignore paths for an artifact across all tools.
 * 
 * For dir-layout kinds (skills), returns directory paths with trailing slash.
 * For file-layout kinds (rules), returns individual file paths.
 */
export function computeArtifactGitignorePaths(
  kindId: string,
  artifactName: string,
  scope: Scope = "project"
): string[] {
  const kind = registry.getKind(kindId);
  if (!kind) return [];

  const paths: string[] = [];

  for (const tool of registry.allTools()) {
    const mapping = registry.resolveMapping(tool.name, kindId);
    if (!mapping) continue;

    // Build template variables
    // For dir-layout kinds, {name} and {stem} are the directory name
    // For file-layout kinds, we need to include the extension
    const ext = mapping.ext ?? (kind.layout === "file" ? ".md" : "");
    
    const vars: TemplateVars = {
      base: tool.basePath[scope],
      home: os.homedir(),
      stem: artifactName,
      ext,
      name: artifactName,
      relative: `${kindId}s/${artifactName}${ext}`,
      kind: kindId,
    };

    // Expand the path template
    const pathTemplate = typeof mapping.path === "string" 
      ? mapping.path 
      : mapping.path[scope];
    
    try {
      let targetPath = expandTemplate(pathTemplate, scope, vars);
      
      // For dir-layout kinds, ensure trailing slash for directory pattern
      if (kind.layout === "dir" && !targetPath.endsWith("/")) {
        targetPath += "/";
      }
      
      // Only include project-relative paths (skip global/absolute paths)
      if (!path.isAbsolute(targetPath)) {
        paths.push(targetPath);
      }
    } catch {
      // Skip if template expansion fails (e.g., missing variables)
      continue;
    }
  }

  return paths;
}

/**
 * Add gitignore paths for a newly created artifact.
 * Merges with existing managed paths rather than replacing.
 */
export function addArtifactToGitignore(
  projectRoot: string,
  kindId: string,
  artifactName: string,
  scope: Scope = "project"
): void {
  const newPaths = computeArtifactGitignorePaths(kindId, artifactName, scope);
  if (newPaths.length === 0) return;

  const existingPaths = getManagedPaths(projectRoot);
  const mergedPaths = [...new Set([...existingPaths, ...newPaths])];
  
  updateGitignore(projectRoot, mergedPaths);
}

/**
 * Remove gitignore paths for a deleted artifact.
 */
export function removeArtifactFromGitignore(
  projectRoot: string,
  kindId: string,
  artifactName: string,
  scope: Scope = "project"
): void {
  const pathsToRemove = new Set(
    computeArtifactGitignorePaths(kindId, artifactName, scope)
  );
  if (pathsToRemove.size === 0) return;

  const existingPaths = getManagedPaths(projectRoot);
  const filteredPaths = existingPaths.filter((p) => !pathsToRemove.has(p));
  
  updateGitignore(projectRoot, filteredPaths);
}
