/**
 * Gitignore management — update .gitignore with loadout-managed paths.
 *
 * Uses markers to identify the managed section:
 *   # <loadout>
 *   ...managed paths...
 *   # </loadout>
 */

import * as path from "node:path";
import { fileExists, readFile, writeFile } from "./fs.js";

const START_MARKER = "# <loadouts>";
const END_MARKER = "# </loadouts>";
const HEADER_COMMENT = "# Auto-generated by loadouts. Do not edit this section.";

/**
 * Update .gitignore with loadout-managed paths.
 *
 * - Creates .gitignore if it doesn't exist
 * - Adds or updates the managed section between markers
 * - Preserves all user content outside the markers
 * - Removes the section entirely if managedPaths is empty
 */
export function updateGitignore(
  projectRoot: string,
  managedPaths: string[]
): void {
  const gitignorePath = path.join(projectRoot, ".gitignore");

  // Always include the state file
  const allPaths = [".loadouts/.state.json", ...managedPaths];

  // Sort and deduplicate
  const uniquePaths = [...new Set(allPaths)].sort();

  // Build the managed section content
  const managedSection =
    uniquePaths.length > 0
      ? `${START_MARKER}\n${HEADER_COMMENT}\n${uniquePaths.join("\n")}\n${END_MARKER}`
      : "";

  if (!fileExists(gitignorePath)) {
    // Create new .gitignore with just the managed section
    if (managedSection) {
      writeFile(gitignorePath, managedSection + "\n");
    }
    return;
  }

  // Read existing content
  const content = readFile(gitignorePath);

  // Find existing managed section
  const startIdx = content.indexOf(START_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    // Replace existing section
    const before = content.slice(0, startIdx).trimEnd();
    const after = content.slice(endIdx + END_MARKER.length).trimStart();

    const parts = [before];
    if (managedSection) {
      parts.push(managedSection);
    }
    if (after) {
      parts.push(after);
    }

    // Join with appropriate newlines
    let newContent = parts.filter(Boolean).join("\n\n");
    if (!newContent.endsWith("\n")) {
      newContent += "\n";
    }

    writeFile(gitignorePath, newContent);
  } else {
    // No existing section — append the managed section
    if (!managedSection) return;

    let newContent = content.trimEnd();
    newContent += "\n\n" + managedSection + "\n";
    writeFile(gitignorePath, newContent);
  }
}

/**
 * Remove the loadout-managed section from .gitignore.
 */
export function removeGitignoreSection(projectRoot: string): void {
  updateGitignore(projectRoot, []);
}

/**
 * Get the current managed paths from .gitignore (for testing/inspection).
 */
export function getManagedPaths(projectRoot: string): string[] {
  const gitignorePath = path.join(projectRoot, ".gitignore");

  if (!fileExists(gitignorePath)) {
    return [];
  }

  const content = readFile(gitignorePath);
  const startIdx = content.indexOf(START_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) {
    return [];
  }

  const section = content.slice(startIdx + START_MARKER.length, endIdx);
  return section
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"));
}
