/**
 * Gitignore management — per-target .gitignore files.
 *
 * Each tool's output directory (e.g., .claude/, .cursor/) gets its own
 * .gitignore with paths relative to that directory. This ensures:
 *
 *  - All artifacts are ignored regardless of activation state
 *  - Global scope is supported (same mechanism, absolute target dirs)
 *  - The project root .gitignore is not cluttered with tool-specific paths
 *
 * Gitignore is part of the artifact lifecycle (add/delete/import), not the
 * render pipeline. Updates happen when artifacts are created or removed,
 * not when loadouts are activated or synced.
 *
 * Uses markers to identify the managed section:
 *   # <loadouts>
 *   ...managed paths...
 *   # </loadouts>
 */

import * as path from "node:path";
import * as os from "node:os";
import {
  fileExists,
  readFile,
  writeFile,
  listFiles,
  listFilesWithExtension,
  isDirectory,
} from "./fs.js";
import { registry } from "../core/registry.js";
import { expandTemplate, type TemplateVars } from "../core/template.js";
import type { Scope } from "../core/types.js";

const START_MARKER = "# <loadouts>";
const END_MARKER = "# </loadouts>";
const HEADER_COMMENT = "# Auto-generated by loadouts. Do not edit this section.";

// Legacy markers from old naming convention
const LEGACY_START_MARKER = "# <loadout>";
const LEGACY_END_MARKER = "# </loadout>";

// Paths always ignored within .loadouts/
const LOADOUTS_STATE_PATHS = [".fallback-applied", ".state.json"];

const MANAGED_ARTIFACT_KINDS = new Set(["rule", "skill"]);

// ---------------------------------------------------------------------------
// Core write function
// ---------------------------------------------------------------------------

/**
 * Low-level: write the managed section to a specific .gitignore file path.
 */
function updateGitignoreFile(gitignorePath: string, managedPaths: string[]): void {
  // Sort and deduplicate
  const uniquePaths = [...new Set(managedPaths)].sort();

  const managedSection =
    uniquePaths.length > 0
      ? `${START_MARKER}\n${HEADER_COMMENT}\n${uniquePaths.join("\n")}\n${END_MARKER}`
      : "";

  if (!fileExists(gitignorePath)) {
    if (managedSection) {
      writeFile(gitignorePath, managedSection + "\n");
    }
    return;
  }

  const content = readFile(gitignorePath);
  const startIdx = content.indexOf(START_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    // Replace existing section
    const before = content.slice(0, startIdx).trimEnd();
    const after = content.slice(endIdx + END_MARKER.length).trimStart();

    const parts = [before];
    if (managedSection) parts.push(managedSection);
    if (after) parts.push(after);

    let newContent = parts.filter(Boolean).join("\n\n");
    if (!newContent.endsWith("\n")) newContent += "\n";

    writeFile(gitignorePath, newContent);
  } else {
    // No existing section — append
    if (!managedSection) return;

    let newContent = content.trimEnd();
    newContent += "\n\n" + managedSection + "\n";
    writeFile(gitignorePath, newContent);
  }
}

// ---------------------------------------------------------------------------
// Public write functions
// ---------------------------------------------------------------------------

/**
 * Update .gitignore within a specific target directory.
 *
 * @param targetDir - Absolute path to the target directory (e.g., /project/.claude or ~/.claude)
 * @param relativePaths - Paths relative to targetDir (e.g., ["rules/foo.md", "skills/bar/"])
 */
export function updateTargetGitignore(
  targetDir: string,
  relativePaths: string[]
): void {
  updateGitignoreFile(path.join(targetDir, ".gitignore"), relativePaths);
}

/**
 * Update .loadouts/.gitignore with state file entries.
 * Always includes .state.json and .fallback-applied.
 */
export function updateLoadoutsGitignore(loadoutsDir: string): void {
  updateGitignoreFile(path.join(loadoutsDir, ".gitignore"), LOADOUTS_STATE_PATHS);
}

// ---------------------------------------------------------------------------
// Path computation
// ---------------------------------------------------------------------------

/**
 * Compute gitignore paths for an artifact, grouped by target directory.
 *
 * Returns a Map of targetBase (as stored in tool.basePath[scope]) →
 * relative paths within that directory.
 *
 * Instruction artifacts (CLAUDE.md, AGENTS.md) that resolve outside the
 * tool's base directory are automatically excluded.
 */
export function computeArtifactGitignorePaths(
  kindId: string,
  artifactName: string,
  scope: Scope = "project"
): Map<string, string[]> {
  const kind = registry.getKind(kindId);
  if (!kind) return new Map();

  const byTarget = new Map<string, string[]>();

  for (const tool of registry.allTools()) {
    if (!tool.supports.includes(kindId)) continue;

    const mapping = registry.resolveMapping(tool.name, kindId);
    if (!mapping) continue;

    const targetBase = tool.basePath[scope];
    const ext = mapping.ext ?? (kind.layout === "file" ? ".md" : "");

    const vars: TemplateVars = {
      base: targetBase,
      home: os.homedir(),
      stem: artifactName,
      ext,
      name: artifactName,
      relative: `${kindId}s/${artifactName}${ext}`,
      kind: kindId,
    };

    const pathTemplate =
      typeof mapping.path === "string" ? mapping.path : mapping.path[scope];

    try {
      const expandedPath = expandTemplate(pathTemplate, scope, vars);

      // Compute the relative path within the target directory
      const relPath = path.relative(targetBase, expandedPath);

      // Skip if the path escapes the target directory (e.g., instruction
      // artifacts that expand to CLAUDE.md or AGENTS.md at the project root)
      if (relPath.startsWith("..")) continue;

      const existing = byTarget.get(targetBase) ?? [];

      if (kind.layout === "dir") {
        // Dir-layout: use trailing slash so all files within are covered
        existing.push(relPath.endsWith("/") ? relPath : relPath + "/");
      } else {
        existing.push(relPath);
      }

      byTarget.set(targetBase, existing);
    } catch {
      // Skip if template expansion fails
    }
  }

  return byTarget;
}

// ---------------------------------------------------------------------------
// Rebuild
// ---------------------------------------------------------------------------

/**
 * Rebuild gitignore entries for all artifacts in the loadouts directory.
 *
 * Scans all rules and skills and writes per-target .gitignore files so that
 * every artifact is ignored regardless of whether it is currently activated.
 * Called after artifact add/delete/import.
 *
 * @param loadoutsDir  - Absolute path to .loadouts/ or ~/.config/loadouts/
 * @param projectRoot  - Project root for resolving relative target paths
 *                       (unused for global scope since all paths are absolute)
 * @param scope        - "project" or "global"
 */
export function rebuildAllGitignores(
  loadoutsDir: string,
  projectRoot: string,
  scope: Scope
): void {
  const allByTarget = collectArtifactPathsByTarget(loadoutsDir, scope);

  // Ensure all relevant target dirs are updated, even when they now have no
  // managed artifacts. This removes stale managed sections from previous runs.
  const managedTargets = new Set<string>([
    ...getManagedTargetBases(scope),
    ...allByTarget.keys(),
  ]);

  for (const targetBase of managedTargets) {
    const paths = allByTarget.get(targetBase) ?? [];
    const absTargetDir = path.isAbsolute(targetBase)
      ? targetBase
      : path.join(projectRoot, targetBase);
    updateTargetGitignore(absTargetDir, paths);
  }
}

export interface TargetGitignoreMismatch {
  targetDir: string;
  expectedPaths: string[];
  actualPaths: string[];
}

export interface GitignoreHealthReport {
  hasLegacyRootSection: boolean;
  loadoutsStateOutOfDate: boolean;
  targetMismatches: TargetGitignoreMismatch[];
  issues: number;
}

/**
 * Check whether the legacy managed section exists in root .gitignore.
 * Handles both # <loadouts> and older # <loadout> markers.
 */
export function hasLegacyRootGitignoreSection(projectRoot: string): boolean {
  const gitignorePath = path.join(projectRoot, ".gitignore");
  if (!fileExists(gitignorePath)) return false;

  const content = readFile(gitignorePath);
  return (
    hasMarkerSection(content, START_MARKER, END_MARKER) ||
    hasMarkerSection(content, LEGACY_START_MARKER, LEGACY_END_MARKER)
  );
}

/**
 * Inspect gitignore state for a scope and report drift from expected state.
 */
export function inspectGitignoreHealth(
  loadoutsDir: string,
  projectRoot: string,
  scope: Scope
): GitignoreHealthReport {
  const expectedByTarget = collectArtifactPathsByTarget(loadoutsDir, scope);

  const targetBases = new Set<string>([
    ...getManagedTargetBases(scope),
    ...expectedByTarget.keys(),
  ]);

  const targetMismatches: TargetGitignoreMismatch[] = [];
  for (const targetBase of [...targetBases].sort()) {
    const absTargetDir = path.isAbsolute(targetBase)
      ? targetBase
      : path.join(projectRoot, targetBase);

    const expectedPaths = normalizePaths(expectedByTarget.get(targetBase) ?? []);
    const actualPaths = normalizePaths(getManagedPathsFromTarget(absTargetDir));

    if (!samePaths(expectedPaths, actualPaths)) {
      targetMismatches.push({
        targetDir: absTargetDir,
        expectedPaths,
        actualPaths,
      });
    }
  }

  const expectedStatePaths = normalizePaths(LOADOUTS_STATE_PATHS);
  const actualStatePaths = normalizePaths(getManagedPathsFromTarget(loadoutsDir));
  const loadoutsStateOutOfDate = !samePaths(expectedStatePaths, actualStatePaths);

  const hasLegacyRootSection = hasLegacyRootGitignoreSection(projectRoot);

  const issues =
    targetMismatches.length +
    (loadoutsStateOutOfDate ? 1 : 0) +
    (hasLegacyRootSection ? 1 : 0);

  return {
    hasLegacyRootSection,
    loadoutsStateOutOfDate,
    targetMismatches,
    issues,
  };
}

// ---------------------------------------------------------------------------
// Read helpers
// ---------------------------------------------------------------------------

/**
 * Get the current managed paths from a target directory's .gitignore.
 */
export function getManagedPathsFromTarget(targetDir: string): string[] {
  return getManagedPathsFromFile(path.join(targetDir, ".gitignore"));
}

function getManagedPathsFromFile(gitignorePath: string): string[] {
  if (!fileExists(gitignorePath)) return [];

  const content = readFile(gitignorePath);
  const startIdx = content.indexOf(START_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) return [];

  const section = content.slice(startIdx + START_MARKER.length, endIdx);
  return section
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"));
}

// ---------------------------------------------------------------------------
// Migration helper
// ---------------------------------------------------------------------------

/**
 * Remove the legacy loadouts-managed section from the project root .gitignore.
 * Handles both old (# <loadout>) and current (# <loadouts>) markers.
 * Used by the `update` command to migrate from the old single-file approach.
 */
export function removeLegacyRootGitignoreSection(projectRoot: string): void {
  const gitignorePath = path.join(projectRoot, ".gitignore");
  if (!fileExists(gitignorePath)) return;

  let content = readFile(gitignorePath);

  // Remove both new and old marker sections
  content = removeMarkerSection(content, START_MARKER, END_MARKER);
  content = removeMarkerSection(content, LEGACY_START_MARKER, LEGACY_END_MARKER);

  // Clean up excess blank lines
  content = content.replace(/\n{3,}/g, "\n\n").trimEnd();
  if (content) content += "\n";

  writeFile(gitignorePath, content || "");
}

// ---------------------------------------------------------------------------
// Internal utilities
// ---------------------------------------------------------------------------

function removeMarkerSection(
  content: string,
  startMarker: string,
  endMarker: string
): string {
  const startIdx = content.indexOf(startMarker);
  const endIdx = content.indexOf(endMarker);

  if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) return content;

  const before = content.slice(0, startIdx).trimEnd();
  const after = content.slice(endIdx + endMarker.length).trimStart();

  if (before && after) return before + "\n\n" + after;
  return before || after;
}

function hasMarkerSection(
  content: string,
  startMarker: string,
  endMarker: string
): boolean {
  const startIdx = content.indexOf(startMarker);
  const endIdx = content.indexOf(endMarker);
  return startIdx !== -1 && endIdx !== -1 && endIdx > startIdx;
}

function collectArtifactPathsByTarget(
  loadoutsDir: string,
  scope: Scope
): Map<string, string[]> {
  const rulesDir = path.join(loadoutsDir, "rules");
  const skillsDir = path.join(loadoutsDir, "skills");

  const allByTarget = new Map<string, string[]>();

  for (const file of listFilesWithExtension(rulesDir, ".md")) {
    const name = file.replace(/\.md$/, "");
    mergeIntoMap(allByTarget, computeArtifactGitignorePaths("rule", name, scope));
  }

  for (const name of listFiles(skillsDir).filter((d) =>
    isDirectory(path.join(skillsDir, d))
  )) {
    mergeIntoMap(allByTarget, computeArtifactGitignorePaths("skill", name, scope));
  }

  return allByTarget;
}

function getManagedTargetBases(scope: Scope): string[] {
  const bases = new Set<string>();
  for (const tool of registry.allTools()) {
    if (!tool.supports.some((kind) => MANAGED_ARTIFACT_KINDS.has(kind))) continue;
    bases.add(tool.basePath[scope]);
  }
  return [...bases];
}

function normalizePaths(paths: string[]): string[] {
  return [...new Set(paths)].sort();
}

function samePaths(a: string[], b: string[]): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}

function mergeIntoMap(
  target: Map<string, string[]>,
  source: Map<string, string[]>
): void {
  for (const [key, values] of source) {
    const existing = target.get(key) ?? [];
    target.set(key, [...existing, ...values]);
  }
}

// ---------------------------------------------------------------------------
// Deprecated — kept for migration use in update.ts
// ---------------------------------------------------------------------------

/**
 * @deprecated Use getManagedPathsFromTarget instead.
 * Still used by the update command to detect whether migration is needed.
 */
export function getManagedPaths(projectRoot: string): string[] {
  return getManagedPathsFromFile(path.join(projectRoot, ".gitignore"));
}
